### ISSUE TITLE
Nested directory lookups fail

### ISSUE THREAD

**Issue by jeffkala** [jeffkala/pyurlcheck#12]
```
▶ pyurlcheck ../nautobot/
Traceback (most recent call last):
  File "/Users/jeffkala/Library/Caches/pypoetry/virtualenvs/pyurlcheck-jbPNAqXn-py3.9/bin/pyurlcheck", line 5, in <module>
    main()
  File "/Users/jeffkala/Library/Caches/pypoetry/virtualenvs/pyurlcheck-jbPNAqXn-py3.9/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jeffkala/Library/Caches/pypoetry/virtualenvs/pyurlcheck-jbPNAqXn-py3.9/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jeffkala/Library/Caches/pypoetry/virtualenvs/pyurlcheck-jbPNAqXn-py3.9/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jeffkala/Library/Caches/pypoetry/virtualenvs/pyurlcheck-jbPNAqXn-py3.9/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/jeffkala/Documents/github-clones/pyurlcheck/pyurlcheck/cli.py", line 20, in main
    files_urls = FindUrls(input_data).find_urls()
  File "/Users/jeffkala/Documents/github-clones/pyurlcheck/pyurlcheck/find.py", line 54, in find_urls
    results.update(_parse_file(f"{self.search}{file}"))
  File "/Users/jeffkala/Documents/github-clones/pyurlcheck/pyurlcheck/find.py", line 29, in _parse_file
    file_data = _read_in_file(filepath)
  File "/Users/jeffkala/Documents/github-clones/pyurlcheck/pyurlcheck/find.py", line 9, in _read_in_file
    return Path(file_to_read).read_text().splitlines()
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1255, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1241, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
IsADirectoryError: [Errno 21] Is a directory: '../nautobot/docker'
```

**Comment by jeffkala** [comment]
Update to using os.walk on the directory.
